Cookie policy, Tag manager & Crumb CSRF
DEFRA/ffc-grants-frontend pull request #61
Opened 2021-04-01 15:49 UTC by govTechSatish

Added Cookie policy, Tag manager & Crumb CSRF

2021-04-06 13:00 UTC, paulsimonandrews requested changes
Looking good.

A few changes requested, mostly about removing code we don't need.

2021-04-06 13:00 UTC, paulsimonandrews commented on test/integration/narrow/routes/collaboration.test.js
> +  process.env.COOKIE_PASSWORD = '1234567890123456789012345678901234567890'
This is not needed as it's set in `docker-compose.yaml`. Same for all the other tests below.

2021-04-06 13:00 UTC, paulsimonandrews commented on app/config/index.js
> +  port: Joi.number().default(3000),
Most of this config isn't used and is therefore redundant. I'd prefer not to add config that we aren't using, and to only add it when the features that use it are added.

From what I can tell we only need `cookiePassword`, `cookieOptions` and `googleTagManagerKey` in this PR, so I think the rest should be removed.

2021-04-06 15:48 UTC, govTechSatish commented on app/templates/cookies/cookie-policy.njk
> +        text: "Home",
resolved.

2021-04-07 08:19 UTC, paulsimonandrews approved these changes
LGTM 👍

2021-04-07 08:28 UTC, merged